export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_FORECAST_SUCCESS = 'FETCH_FORECAST_SUCCESS';
export const FETCH_DATA_FAILED = 'FETCH_DATA_FAILED';
export const FETCH_DATA = 'FETCH_DATA';

export const SHOW_MODAL_ABOUT = 'SHOW_MODAL_ABOUT';

export const SET_CITYNAME = 'SET_CITYNAME';